### ISSUE TITLE
Thread-safety

### ISSUE THREAD

**Issue by krystophny** [DDMGNI/GeometricIntegrators.jl#29]
Cache of implicit integrators is not thread-safe. e.g. 

``` 
cache = NonlinearFunctionCacheSIPRK{ST}(D, M, S)
```

Possible solution: pre-generate cache `Base.Threads.nthreads` times and use according to `threadid`.

**Comment by michakraus** [comment]
Unfortunately, it is not that easy. However, ParallelSimulation itself as well as the basic Runge-Kutta methods (DIRK, FIRK, IPRK) are now thread-safe (#40).

**Comment by michakraus** [comment]
PR #50 introduces a new cache mechanism that is fully thread-safe.
