### ISSUE TITLE
Package Name

### ISSUE THREAD

**Issue by ChrisRackauckas** [DDMGNI/GeometricIntegrators.jl#5]
@musm brought up a good point in the Gitter chats that the package may need to be re-named if you want to eventually register it in the package ecosystem. I thought I might as well bring this up because you seem to be promoting it on your personal site, and it would be a bummer to get too deep and then have to rename it!

In case you're not aware, names which are acronyms and abbreviations are not allowed. In fact, this was said by the gatekeeper of the package management system @tkelman:

>abbreviations are usually okay, but ODE and SDE are bad names that probably would be spelled out more if registered today. people not in the field will want to know what the package is for and possibly use it as well. longer names are clearer.

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/59#issuecomment-254072605

Given that, if you'd want to register this package you'd very likely have to change the name so that "people not in the field will want to know what the package is for", i.e. don't abbreviate DAE.

That said, I think something like GeometricIntegrators.jl would work. Just something to think about.

**Comment by michakraus** [comment]
Yes, thanks for pointing that out. Indeed, I had come across this as a possible issue, but didn't really worry about it too much, yet, as I think the package is still a bit too far away from stability for registering it. GeometricIntegrators.jl is probably the way to go, though.
